### ISSUE TITLE
Migrate to a docker component

### ISSUE THREAD

**Issue by kachnitel** [keboola/youtube-extractor-bundle#1]
Needs a migration to Docker
### Possible solutions:

1) ex-generic plugin (like https://github.com/keboola/gex-qualtrics-preparser)
- to parse analytics data, probably the quickest solution
- creating a template will need solid knowledge of the API

2) a simple ex from scratch. Analytics data wouldn't need json parser, non-analytics would need either that or a mapping solution though, which is related to metrics exported. 

The current extractor is terribly sensitive to configuration changes, the API just returns not too helpful errors if it is configured badly. We should either provide solid enough templates, or figure out the errors in the new EX.

**Comment by odinuv** [comment]
component replaced by `keboola.ex-youtube`
